mysite/food/urls.py
from django.urls import path
from . import views
from django.contrib.auth.decorators import login_required

app_name = 'food'  # this set the namespace and all named defined in here are only available for this app, example 'food:update_item'

urlpatterns = [
    # /food  # the following link still work, it's based on function based views
    # path('', views.index,name='index'),   # index contains all items, this is based on function based views

    # index path using class based view, don't forget to add "as_view() in the end" because , this is the particularity of class based view
    path('', login_required(views.IndexClassView.as_view()),
         name='index'),   # index contains all items

    path('item/', views.item, name='item'),    # get all item

    # /food/item/i based on function based view

          #  path('item/<int:item_id>/', views.detail,
                    #  name='detail'),  # get specific item
    
    # /food/item/i  based on class views
    path('item/<int:pk>/', views.DetailClassView.as_view(),
         name='detail'),  # get specific item

    # /food/add
          #path('add', views.create_item, name='create_item'),
     #/food/add  replaced by a class based view as follow:

     path('add', views.CreateItem.as_view(), name='create_item'),
    # edit item
    path('update/<int:item_id>/', views.update_item, name='update_item'),
    # delete item

    path('delete/<int:item_id>/', views.delete_item, name='delete_item'),
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from users import views as user_views
from django.contrib.auth import views as authentication_views
#Serving files uploaded by a user during development
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('food/',include('food.urls')),
    path('register/', user_views.register, name='register'),
    path('login/', authentication_views.LoginView.as_view(template_name='users/login.html'), name='login'),  #"as_view" here because it's a class based view
    path('logout/', authentication_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    path('profile/', user_views.profilepage, name='profile'),

    

]

# Serving files uploaded by a user during development
urlpatterns += [
    # ... the rest of your URLconf goes here ...
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mysite/food/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
# Create your models here.
class Item(models.Model):   # this class will create a table called Item
    # by  default, when you query this model, it will returns with 'Item.objects.all()' something like "<QuerySet [<Item: Item object (1)>, <Item: Item object (2)>]>", if you want a different behavior, for example the name of the item, Do as follows:
    def __str__(self):
        return self.item_name
    user_name = models.ForeignKey(User,on_delete=models.CASCADE,default=18) # this line of code creates relationship between  USER and item models, "on_delete" means, if the user is deleted, the item is automatically deleted as well
    item_name = models.CharField(max_length=200)
    item_desc = models.CharField(max_length=200)
    item_price= models.IntegerField()
    item_image= models.CharField(max_length=500 ,default="https://www.shutterstock.com/shutterstock/photos/2145440019/display_1500/stock-vector-exciting-new-cafe-bar-restaurant-menu-coming-soon-flat-design-2145440019.jpg") # image url is stored over here; if it weren't a link, you would have needed to install  pillow package

   # the following line is because  in case of a class based view, we also need to mention the Url where we want django to redirect Us when the item is created
    def get_absolute_url(self):
        return reverse("food:detail", kwargs={"pk": self.pk})  # "food:detail" is where we want to be redirected
    

mysite/food/forms.py
from django import forms
from .models import Item

class ItemForm(forms.ModelForm):
    class Meta:
        model = Item
        fields = ['item_name','item_desc','item_price' ,'item_image']  # fields that should be present in the form, we don't need to have all fields

mysite/food/views.py
from django.shortcuts import render , redirect
from django.http import HttpResponse 
from .models import Item
from .forms import ItemForm
from django.template import loader
from django.contrib.auth.decorators import login_required
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView
# Create your views here.
## first method for index view
'''def index(request):
    item_list = Item.objects.all()
    template = loader.get_template('food/index.html') # you don't need to add the directory named "templates"
    context ={
        'item_list' : item_list,

    }
    return HttpResponse (template.render(context,request))
    '''
## second method for index view (optimal)


@login_required  # decorator that means the connexion is mandatory
def index(request):
    item_list = Item.objects.all()
    context ={
        'item_list' : item_list,
    }
    return render(request,'food/index.html',context)

# As index view above just list a list of items , we can rewrite it using class based views  as follow



class IndexClassView(ListView):
    model = Item
    template_name = 'food/index.html'
    context_object_name = 'item_list'


##################
def item(request):
    
    return HttpResponse ('<h1><u>This is an item view</u></h1> ')


def detail(request,item_id):
   item = Item.objects.get(pk=item_id)
   context = {
       'item': item,
    }
    #return HttpResponse("This is item no/id %s" %item_id)
   return render(request,'food/detail.html',context)

# class based view for details
class DetailClassView(DetailView):
    model = Item
    template_name = 'food/detail.html'
    # as you can see, we don't need to pass a context any more, django will be able to identified a record  by using "object" or "item" (because we are dealing with Item Model) in the template
    #context_object_name = 'item' 

def create_item(request):
    form = ItemForm(request.POST or None)

    if form.is_valid() :
        form.save()
        return redirect('food:index')  # this means to follow the path that the name is "index", and the namespace= "food" ans defined in the url views by app_name=food
    return render(request,'food/item-form.html',{'form': form}) # the last part is the context

## class based for "create_item" so we can easily associate Apps
class CreateItem(CreateView):
    model = Item
    fields = ['item_name','item_desc','item_price','item_image']
    template_name = 'food/item-form.html'
    def form_valid(self,form):
        form.instance.user_name = self.request.user  # this is kind of association User

        return super().form_valid(form)


def update_item(request, item_id):
    item = Item.objects.get(pk=item_id)  # or  Item.objects.get(id=item_id)
    form = ItemForm(request.POST or None, instance=item) #this automatically fills form with data collected from the database
    context = {
        'item': item,
        'form': form,
    }

    if form.is_valid():
        form.save()
        # this means to follow the path that the name is "index", and the namespace= "food" ans defined in the url views by app_name=food
        return redirect('food:index')
    return render(request, 'food/item-form.html',context)


def delete_item(request, item_id):
    item = Item.objects.get(pk=item_id)  # or  Item.objects.get(id=item_id)
    # this automatically fills form with data collected from the database
    form = ItemForm(request.POST or None, instance=item)
    context = {
        'item': item,
        'form': form,
    }
    if request.method == 'POST':
        item.delete()
        # this means to follow the path that the name is "index", and the namespace= "food" ans defined in the url views by app_name=food
        return redirect('food:index')
    return render(request, 'food/item-delete.html', context)

mysite/food/templates/food/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" href="{% static 'food/style.css' %}">
    <!--<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
-->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
    <title>FoodApp</title>

</head>
<body>
    
  <nav class="navbar navbar-dark bg-dark">
    <a href="{% url 'food:index'  %}" class="navbar-brand">FoodApp</a>
    <div class="navbar" >
      <a class="nav-item nav-link" href="{% url 'food:create_item'  %}">Add Item</a>
      <a class="nav-item nav-link" href="#">Delete Item</a>
      <a class="nav-item nav-link" href="#">View Item</a>  
      {% if user.is_authenticated %}
        <a class="nav-item nav-link" href="{% url 'logout' %}">Logout</a>
        <a class="nav-item nav-link" href="{% url 'profile' %}">Profile</a> 
      {% else %}      
        <a href="{% url 'login' %}">Login</a>
      {% endif %}
    </div>
  </nav>
 
  {% if messages%}
      {% for message in messages%}
        <div class="alert alert-{{ message.tags}}">
          {{message}}
        </div>
      {%endfor%}
  {% endif %}

  {% block body%}
  {% endblock %}
</body>
</html>

mysite/food/templates/food/detail.html
{%  extends "food/base.html" %}  <!--this include the base template to the code then move to "block body"- "end block" -->
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>

    {% block body %}

    <div class="container">
        <div class="row"> 
            <!--
            <div class="col-md-6"> 
        
                <img class="card" height="300px"  src=" {{item.item_image}}" />
            </div>
            <div class="col-md-6"> 
        
               <h1> {{item.item_name}} </h1> 
               <h1> {{item.item_desc}} </h1> 
               <h1> ${{item.item_price}} </h1> 
               <a href="{% url 'food:delete_item' item.id %}" class="btn btn-danger"> Delete </a>
             
            </div>
        -->
        <div class="col-md-6"> 
        
                <img class="card" height="300px"  src=" {{object.item_image}}" />
            </div>
            <div class="col-md-6"> 
        
               <h1> {{object.item_name}} </h1> 
               <h1> {{object.item_desc}} </h1> 
               <h1> ${{object.item_price}} </h1> 
               <a href="{% url 'food:delete_item' object.id %}" class="btn btn-danger"> Delete </a>
             
            </div>
        </div>
        
    </div>



    {% endblock %}
</body>
</html>

mysite/food/templates/food/index.html
{%  extends "food/base.html" %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>First template</title>
</head>
<body>

  {% block body%}

    <h1>List of Items</h1>


    {%  for item in item_list        %}
    
    <div class="row"> 
      <div class="col-md-3 offset-md-2 my-2"> <!-- on a medium device we need offset of 2 {{item.item_image}}-->
       <!-- <img class="card" height="150px" src=" {% static 'food/images/burger.jpg' %}" />  (this is for local and static images)-->
       
 
       
       
       <img class="card" height="150px" width='200px' src=" {{item.item_image}}" />
      
      </div>
      <div class="col-md-4 my-2"> 
          <h3>{{item.item_name}}</h3>
          <h5>{{item.item_desc}}</h5>
          <h6>${{item.item_price}}</h6>
          <!-- user_name is only possible after chap61 with associating user to the model-->
           <h6>{{item.user_name}}</h6>
      </div>
      <div class="col-md-2 my-2"> 
        <a href="{% url 'food:detail' item.id  %}" class="btn btn-success"> Details</a>
      </div>
    </div>
 
  {% endfor %}
  
  {% endblock %}
</body>
</html>


mysite/food/templates/food/item-delete.html
{%  extends "food/base.html" %}

{% block body%}
<h2> Are you sure you want to delete   <b> {{item.item_name}} </b></h2>
<form method='POST'> 
 {% csrf_token %} <!-- prevent cross site scripting while using forms -->

{{form}}


<button type="submit" class="btn btn-danger"> delete </button>
<a  href="{% url 'food:index' %}" class="btn btn-warning"> cancel</a>

</form>
{% endblock%}

mysite/food/templates/food/item-form.html
{%  extends "food/base.html" %}
{% block body %}
 <div class="container mt-3">
    <div class="row">
      <div class="col-md-6 offset-md-3">
        <div class="card">
          <div class="card-header text-white bg-info">
            <div class="card-title">
              Add item
            </div>
           
          </div>
          <div class="card-body">
              <form method="POST">
                  {% csrf_token %}
                 <!-- we can access a form globally by using this {{form}} or using the below syntax to access fields individually--> 
                 {% for field in form%}
                    <div class="form-group">
                      {{field.name}} 
                      <br/>
                      {{field}} 
                    
                    </div>
                  {% endfor%}
                  <button class="btn-info" type="submit">Save</button> <!-- btn-info returns blue color-->
              </form>
          </div>
        </div>
      </div>
    </div>
  </div>


{% endblock %}